cluster:
  domain: staraps.com
  region: us-east-1
  # IP for the auth.<cluster-domain> alias (match the ClusterIP in the infra namespace)
  hostIP: 192.168.1.85

k3s:
  disable: []
  serverFlags: []

keycloak:
  realm: infra

routes:
  argocd: argocd
  grafana: grafana
  headlamp: infra
  keycloak: auth
  loki: logs

services:
  namespace: infra
