apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  namespace: infra
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      zipkin: {}

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1000

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        const_labels:
          service: opentelemetry-collector
      logging:
        loglevel: debug

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [batch]
          exporters: [prometheus, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]
