apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ernesto/k8s-boostrap.git
    targetRevision: HEAD
    path: infra/services/observability/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: traefik.io
      kind: IngressRoute
      name: argocd
      namespace: argocd
      jsonPointers:
        - /spec/routes
