apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.mydomain.com
  oidc.config: |
    name: Keycloak
    issuer: https://auth.mydomain.com/realms/master
    clientID: argocd
    enablePKCEAuthentication: "true"
    refreshTokenThreshold: 2m
    requestedScopes:
      - openid
      - profile
      - email
      - groups
  repositories: |
    - url: https://github.com/your-org/private-repo
      usernameSecret:
        name: argocd-private-github
        key: username
      passwordSecret:
        name: argocd-private-github
        key: password
