apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc-secret
  namespace: infra
type: Opaque
stringData:
  OIDC_CLIENT_ID: headlamp
  OIDC_CLIENT_SECRET: CHANGEME
  OIDC_ISSUER_URL: https://auth.mydomain.com/realms/master