apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          # Keep the IP below in sync with config.yaml:cluster.hostIP
          192.168.1.85 auth.cluster.local
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 8.8.8.8 1.1.1.1
        cache 30
        loop
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
