---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credential-provider
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-credential-provider
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-credential-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-credential-provider
subjects:
  - kind: ServiceAccount
    name: ecr-credential-provider
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ecr-credential-provider
  namespace: kube-system
  labels:
    app: ecr-credential-provider
spec:
  selector:
    matchLabels:
      app: ecr-credential-provider
  template:
    metadata:
      labels:
        app: ecr-credential-provider
    spec:
      serviceAccountName: ecr-credential-provider
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: credential-provider
          image: yuyinws/ecr-credential-provider:v1.0.0
          env:
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: AWS_ACCOUNT_ID
              value: "${AWS_ACCOUNT_ID}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: SECRET_NAME
              value: "ecr-registry"
            - name: SECRET_NAMESPACE
              value: "default"
            - name: REFRESH_INTERVAL
              value: "6h"
          imagePullPolicy: Always
          securityContext:
            privileged: true
      tolerations:
        - operator: Exists
