apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: infra
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
