apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: infra
data:
  KEYCLOAK_HTTP_PORT: "8080"
  KEYCLOAK_HTTPS_PORT: "8443"
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres.infra.svc.cluster.local:5432/postgres
  KC_DB_USERNAME: postgres
  KC_PROXY: edge
  KC_HOSTNAME_STRICT: "false"
  KEYCLOAK_DATABASE_HOST: postgres.infra.svc.cluster.local
  KEYCLOAK_DATABASE_PORT: "5432"
  KEYCLOAK_DATABASE_NAME: postgres
  KEYCLOAK_DATABASE_USER: postgres
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
