apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nuclio

resources:
  - namespace.yaml
  - platform-config.yaml
  - rbac.yaml

helmCharts:
  - name: nuclio
    repo: https://nuclio.github.io/nuclio/charts
    version: latest
    releaseName: nuclio
    valuesFile: values.yaml