apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.mydomain.com`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: grafana
          port: 3000
  tls:
    certResolver: le
