apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: infra
type: Opaque
stringData:
  GRAFANA_OIDC_CLIENT_SECRET: ${GRAFANA_OIDC_CLIENT_SECRET}
  GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}